### ISSUE TITLE
FAILED tests/test_datasets.py::TestSen1Floods11NonGeo::test_dataset_sample - KeyError: 'location'

### ISSUE THREAD

**Issue by romeokienzler** [IBM/terratorch#310]
**Describe the issue**
when running tests on main we get 
FAILED tests/test_datasets.py::TestSen1Floods11NonGeo::test_dataset_sample - KeyError: 'location'

**Comment by Joao-L-S-Almeida** [comment]
I updated the branch to the most recent commit (ea44763710a0eae49cab14bc8e5585df3afecde7), defined PYTHONPATH and ran `pytest -s tests/test_datasets.py`, but I couldn't replicate the issue.

**Comment by romeokienzler** [comment]
still getting it, this is what I did:

git clone git@github.com:IBM/terratorch.git
cd terratorch
git checkout 9a00845544e9ad4652eb1f9ada0dc8b98b9a603c
python -m venv .venv
source ./.venv/bin/activate
pip install -U .
pytest
